name: Executar proves Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  proves:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositori
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instal·lar dependències
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt || true

    - name: Executar proves amb unittest
      run: |
        python -m unittest discover -v
